/* Copyright (c) Neo
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/xiongyu0523/azure-sphere-arducam-mini-2mp-plus.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// See https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies for more information on how to use hardware abstractions
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../sample_hardware.json.  Do not edit it directly.

#pragma once
#include "mt3620_rdb.h"

// Connect CS to RDB Header1 Pin12(GPIO4)
#define ARDUCAM_CS MT3620_RDB_HEADER1_PIN12_GPIO

// Connect I2C to RDB Header2 Pin1(SDA) and Pin7(SCL)
#define ARDUCAM_I2C MT3620_RDB_HEADER2_ISU0_I2C

// Connect SPI to RDB Header4 Pin5(MISO), Pin7(SCLK), Pin11(MOSI)
#define ARDUCAM_SPI MT3620_RDB_HEADER4_ISU1_SPI

